### ISSUE TITLE
MKR1000 Update Firmware FAILS!!!!

### ISSUE THREAD

**Issue by KevanE** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#41]
Upload of firmware to MKR1000 fails everytime for reasons listed below.   Please support this issue!!!!!!

java.lang.Exception: Error while erasing flash memory.
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.eraseFlash(FlasherSerialClient.java:152)
	at cc.arduino.plugins.wifi101.flashers.java.WINCFlasher.updateFirmware(WINCFlasher.java:72)
	at cc.arduino.plugins.wifi101.UpdaterImpl$2.run(UpdaterImpl.java:206)

**Comment by Rocketct** [comment]
Hi @KevanE which version of the IDE are you using? have you upload the correct firmware update sketch on the MKR1000? which firmware version are you trying to upload on the board?

**Comment by Rocketct** [comment]
Closed due to lack of feedback! @KevanE please reopen if you need
