### ISSUE TITLE
WiFi101 Firmware Updater FAILS!!!!

### ISSUE THREAD

**Issue by KevanE** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#42]
After updatefirmware sketch is uploaded to MKR1000 the firmware fails to upload for the following reasons....

java.lang.Exception: Error while erasing flash memory.
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.eraseFlash(FlasherSerialClient.java:152)
	at cc.arduino.plugins.wifi101.flashers.java.WINCFlasher.updateFirmware(WINCFlasher.java:72)
	at cc.arduino.plugins.wifi101.UpdaterImpl$2.run(UpdaterImpl.java:206)

Please Help

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/issues/41
