### ISSUE TITLE
MKR1000 Flash Memory FAILS !!!

### ISSUE THREAD

**Issue by KevanE** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#43]
Firmware Update fails after upload of firmwareupdate sketch for the following reason...
java.lang.Exception: Error while erasing flash memory.
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.eraseFlash(FlasherSerialClient.java:152)
	at cc.arduino.plugins.wifi101.flashers.java.WINCFlasher.updateFirmware(WINCFlasher.java:72)
	at cc.arduino.plugins.wifi101.UpdaterImpl$2.run(UpdaterImpl.java:206)

Please advise!!!!!!!!!!!!!!!!!!!

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/issues/41
