### ISSUE TITLE
Can't communicate with programmer!

### ISSUE THREAD

**Issue by ysk8** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#9]
Today I tried to update the firmware but all the time I get this error:

**_java.lang.Exception: Can't communicate with programmer!
	at cc.arduino.plugins.unowifi.flashers.cli.CLIFlasher.testConnection(CLIFlasher.java:100)
	at cc.arduino.plugins.unowifi.UpdaterImpl$2.run(UpdaterImpl.java:112)_**

The port chosen one is the correct. The IDE is 1.8.3 running in a macOS Sierra Version 10.12.6

<img width="540" alt="screen shot 2017-07-26 at 18 37 59" src="https://user-images.githubusercontent.com/4340660/28648274-461be3dc-7232-11e7-91d7-b66e6b24458e.png">

**Comment by ysk8** [comment]
My mistake, I had forgot upload the EspRecovery sketch. :D
